"""Crear tablas

Revision ID: 048127734cb9
Revises: 
Create Date: 2025-02-21 11:09:30.680513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048127734cb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Female', 'Male', name='genderenum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('spending_score', sa.Integer(), nullable=True),
    sa.Column('work_experience', sa.Integer(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession')
    op.drop_table('customer')
    # ### end Alembic commands ###
