"""Modificacion tabla clientes

Revision ID: 468da7851746
Revises: 048127734cb9
Create Date: 2025-02-21 11:13:24.643525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468da7851746'
down_revision: Union[str, None] = '048127734cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('profession_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'profession', ['profession_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'profession_id')
    # ### end Alembic commands ###
